#:schema node_modules/wrangler/config-schema.json
name = "chousei"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "chousei-db"
database_id = "876d56d7-77d5-483f-90e2-93d8f2d41130"
migrations_dir = "d1-migrations"

[vars]
ADMIN_PASSWORD = "admin123"
NEXT_PUBLIC_APP_URL = "https://chousei.pages.dev"
